// ============================================
// BEAST ROYALE - BEAST DEFINITIONS
// ============================================

import { BeastDefinition, AbilityDefinition } from './types.js';

// ============================================
// ABILITY DEFINITIONS
// ============================================

const ABILITIES: Record<string, AbilityDefinition> = {
  // === AOE BEASTS (5) ===
  shell_slam: {
    id: 'shell_slam',
    name: 'Shell Slam',
    type: 'aoe',
    description: 'Become invulnerable briefly, then release a massive shockwave',
    cooldown: 10000,
    aoe: {
      radius: 180,
      damage: 15,
      knockback: 600,
      delay: 500,
      invulnerableDuring: true,
    },
  },

  one_two_punch: {
    id: 'one_two_punch',
    name: 'One-Two Punch',
    type: 'aoe',
    description: 'Melee combo with stagger - second punch has huge knockback',
    cooldown: 7000,
    aoe: {
      radius: 80,
      damage: 20,
      knockback: 700,
      stunDuration: 300,
    },
  },

  hibernate_rage: {
    id: 'hibernate_rage',
    name: 'Hibernate Rage',
    type: 'aoe',
    description: 'Fall asleep and become invulnerable for 3s, then massive AOE',
    cooldown: 15000,
    aoe: {
      radius: 200,
      damage: 25,
      knockback: 700,
      delay: 3000,
      invulnerableDuring: true,
    },
  },

  scream: {
    id: 'scream',
    name: 'AAAAAH!',
    type: 'aoe',
    description: 'Ear-splitting scream that stuns and knocks back enemies in a cone',
    cooldown: 5000,
    aoe: {
      radius: 150,
      damage: 10,
      knockback: 450,
      stunDuration: 800,
    },
  },

  existential_crisis: {
    id: 'existential_crisis',
    name: 'Existential Crisis',
    type: 'aoe',
    description: 'All nearby beasts question their existence (stun)',
    cooldown: 8000,
    aoe: {
      radius: 140,
      damage: 5,
      knockback: 200,
      stunDuration: 1500,
    },
  },

  // === PROJECTILE BEASTS (8) ===
  tongue_lash: {
    id: 'tongue_lash',
    name: 'Tongue Lash',
    type: 'projectile',
    description: 'Spit a slime glob that creates a slow zone on impact',
    cooldown: 8000,
    projectile: {
      behavior: 'straight',
      speed: 400,
      damage: 10,
      knockback: 200,
      piercing: false,
      count: 1,
      lifetime: 2000,
      radius: 20,
      effect: {
        type: 'slow_zone',
        radius: 100,
        duration: 5000,
        slowAmount: 0.5,
      },
    },
  },

  chain_lightning: {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    type: 'projectile',
    description: 'Piercing bolt that chains to nearby enemies',
    cooldown: 10000,
    projectile: {
      behavior: 'chain',
      speed: 800,
      damage: 15,
      knockback: 200,
      piercing: true,
      count: 1,
      chainRange: 150,
      chainCount: 3,
      lifetime: 1500,
      radius: 10,
    },
  },

  spine_barrage: {
    id: 'spine_barrage',
    name: 'Spine Barrage',
    type: 'projectile',
    description: 'Fire 5 needles in a spread pattern',
    cooldown: 6000,
    projectile: {
      behavior: 'spread',
      speed: 600,
      damage: 8,
      knockback: 100,
      piercing: false,
      count: 5,
      spreadAngle: Math.PI / 3,  // 60 degrees
      lifetime: 1500,
      radius: 8,
    },
  },

  moocus_missile: {
    id: 'moocus_missile',
    name: 'Moo-cus Missile',
    type: 'projectile',
    description: 'Large slow glob that creates a big slow zone',
    cooldown: 11000,
    projectile: {
      behavior: 'straight',
      speed: 350,
      damage: 5,
      knockback: 50,
      piercing: false,
      count: 1,
      lifetime: 3000,
      radius: 30,
      effect: {
        type: 'slow_zone',
        radius: 150,
        duration: 7000,
        slowAmount: 0.4,
      },
    },
  },

  ink_bomb: {
    id: 'ink_bomb',
    name: 'Ink Bomb',
    type: 'projectile',
    description: 'Creates a vision-blocking ink splat on impact',
    cooldown: 9000,
    projectile: {
      behavior: 'arc',
      speed: 400,
      damage: 10,
      knockback: 150,
      piercing: false,
      count: 1,
      lifetime: 2500,
      radius: 25,
      effect: {
        type: 'vision_block',
        radius: 120,
        duration: 4000,
      },
    },
  },

  quasar_blast: {
    id: 'quasar_blast',
    name: 'Quasar Blast',
    type: 'projectile',
    description: 'Slightly homing cosmic fireball',
    cooldown: 10000,
    projectile: {
      behavior: 'homing',
      speed: 450,
      damage: 18,
      knockback: 300,
      piercing: false,
      count: 1,
      homingStrength: 0.3,
      lifetime: 3000,
      radius: 20,
    },
  },

  crystal_shard: {
    id: 'crystal_shard',
    name: 'Crystal Shard',
    type: 'projectile',
    description: 'Fast, high damage single shot',
    cooldown: 6000,
    projectile: {
      behavior: 'straight',
      speed: 700,
      damage: 25,
      knockback: 400,
      piercing: false,
      count: 1,
      lifetime: 1500,
      radius: 12,
    },
  },

  royal_volley: {
    id: 'royal_volley',
    name: 'Royal Volley',
    type: 'projectile',
    description: '3 slow homing pigeons',
    cooldown: 8000,
    projectile: {
      behavior: 'homing',
      speed: 300,
      damage: 8,
      knockback: 150,
      piercing: false,
      count: 3,
      spreadAngle: Math.PI / 4,
      homingStrength: 0.5,
      lifetime: 4000,
      radius: 18,
    },
  },

  // === MOVEMENT BEASTS (7) ===
  slinky_dash: {
    id: 'slinky_dash',
    name: 'Slinky Dash',
    type: 'movement',
    description: '300px invulnerable dash forward',
    cooldown: 5000,
    movement: {
      movementType: 'dash',
      distance: 300,
      invulnerable: true,
    },
  },

  flap_burst: {
    id: 'flap_burst',
    name: 'Flap Burst',
    type: 'movement',
    description: 'Short dash with knockback at the end',
    cooldown: 6000,
    movement: {
      movementType: 'dash',
      distance: 150,
      knockbackOnEnd: 400,
      invulnerable: false,
    },
  },

  rewind: {
    id: 'rewind',
    name: 'Rewind',
    type: 'movement',
    description: 'Teleport to your position from 3 seconds ago',
    cooldown: 15000,
    movement: {
      movementType: 'rewind',
      rewindDuration: 3000,
      invulnerable: true,
    },
  },

  shadow_step: {
    id: 'shadow_step',
    name: 'Shadow Step',
    type: 'movement',
    description: 'Become invisible and teleport a short distance',
    cooldown: 9000,
    movement: {
      movementType: 'teleport',
      distance: 200,
      invulnerable: true,
    },
  },

  phase_shift: {
    id: 'phase_shift',
    name: 'Phase Shift',
    type: 'movement',
    description: 'Become intangible and fast for 2 seconds',
    cooldown: 12000,
    movement: {
      movementType: 'phase',
      duration: 2000,
      speedMultiplier: 1.5,
      invulnerable: true,
    },
  },

  quick_swap: {
    id: 'quick_swap',
    name: 'Quick Swap',
    type: 'movement',
    description: 'Teleport to the nearest enemy',
    cooldown: 12000,
    movement: {
      movementType: 'teleport',
      distance: 400,  // Max range
      invulnerable: false,
    },
  },

  wheel_boost: {
    id: 'wheel_boost',
    name: 'Wheel Boost',
    type: 'movement',
    description: '2x speed and knockback immunity for 2 seconds',
    cooldown: 7000,
    movement: {
      movementType: 'speed_boost',
      duration: 2000,
      speedMultiplier: 2.0,
      invulnerable: false,  // Not invuln, just knockback immune
    },
  },

  // Legacy abilities (fallbacks)
  belly_flop: {
    id: 'belly_flop',
    name: 'Belly Flop',
    type: 'aoe',
    description: 'Leap forward and create an explosion on landing',
    cooldown: 8000,
    aoe: {
      radius: 120,
      damage: 15,
      knockback: 550,
    },
  },

  neck_whip: {
    id: 'neck_whip',
    name: 'Neck Whip',
    type: 'aoe',
    description: 'Swing head in a full circle with massive range',
    cooldown: 7000,
    aoe: {
      radius: 150,
      damage: 12,
      knockback: 400,
    },
  },

  copycat: {
    id: 'copycat',
    name: 'Copycat',
    type: 'special',
    description: 'Temporarily gain the special move of the nearest enemy',
    cooldown: 12000,
  },

  good_boy_paradox: {
    id: 'good_boy_paradox',
    name: 'Good Boy Paradox',
    type: 'special',
    description: 'Create a duplicate that mimics your movements inversely',
    cooldown: 12000,
  },

  // === NEW ABILITIES (10 more) ===
  laser_beam: {
    id: 'laser_beam',
    name: 'Laser Beam',
    type: 'projectile',
    description: 'Fire a piercing laser that damages all in its path',
    cooldown: 6000,
    projectile: {
      behavior: 'straight',
      speed: 1200,
      damage: 18,
      knockback: 150,
      piercing: true,
      count: 1,
      lifetime: 800,
      radius: 8,
    },
  },

  super_bounce: {
    id: 'super_bounce',
    name: 'Super Bounce',
    type: 'movement',
    description: 'Bounce high and land with impact damage',
    cooldown: 5000,
    movement: {
      movementType: 'dash',
      distance: 250,
      duration: 400,
      invulnerable: true,
    },
  },

  thunder_stomp: {
    id: 'thunder_stomp',
    name: 'Thunder Stomp',
    type: 'aoe',
    description: 'Slam the ground creating a massive shockwave',
    cooldown: 9000,
    aoe: {
      radius: 160,
      damage: 20,
      knockback: 650,
      stunDuration: 400,
    },
  },

  acorn_barrage: {
    id: 'acorn_barrage',
    name: 'Acorn Barrage',
    type: 'projectile',
    description: 'Throw a rapid stream of acorns',
    cooldown: 4000,
    projectile: {
      behavior: 'spread',
      speed: 700,
      damage: 6,
      knockback: 80,
      piercing: false,
      count: 7,
      spreadAngle: Math.PI / 2,
      lifetime: 1200,
      radius: 6,
    },
  },

  rocket_boost: {
    id: 'rocket_boost',
    name: 'Rocket Boost',
    type: 'movement',
    description: 'Blast forward at incredible speed',
    cooldown: 7000,
    movement: {
      movementType: 'dash',
      distance: 400,
      duration: 300,
      invulnerable: true,
    },
  },

  sonic_screech: {
    id: 'sonic_screech',
    name: 'Sonic Screech',
    type: 'aoe',
    description: 'Emit a disorienting screech that stuns nearby enemies',
    cooldown: 8000,
    aoe: {
      radius: 130,
      damage: 8,
      knockback: 300,
      stunDuration: 1200,
    },
  },

  bubble_blast: {
    id: 'bubble_blast',
    name: 'Bubble Blast',
    type: 'projectile',
    description: 'Launch slow-moving bubbles that trap enemies',
    cooldown: 6000,
    projectile: {
      behavior: 'homing',
      speed: 300,
      damage: 5,
      knockback: 100,
      piercing: false,
      count: 3,
      spreadAngle: Math.PI / 4,
      lifetime: 3000,
      radius: 25,
      effect: {
        type: 'slow_zone',
        radius: 60,
        duration: 2000,
        slowAmount: 0.3,
      },
    },
  },

  spirit_walk: {
    id: 'spirit_walk',
    name: 'Spirit Walk',
    type: 'movement',
    description: 'Become ethereal and pass through enemies',
    cooldown: 10000,
    movement: {
      movementType: 'phase',
      duration: 2500,
      speedMultiplier: 1.5,
    },
  },

  magnetic_pull: {
    id: 'magnetic_pull',
    name: 'Magnetic Pull',
    type: 'aoe',
    description: 'Pull all nearby enemies towards you',
    cooldown: 9000,
    aoe: {
      radius: 180,
      damage: 5,
      knockback: -500,  // Negative = pull towards
    },
  },

  disco_flash: {
    id: 'disco_flash',
    name: 'Disco Flash',
    type: 'aoe',
    description: 'Dazzling display that stuns and damages all nearby',
    cooldown: 11000,
    aoe: {
      radius: 170,
      damage: 12,
      knockback: 250,
      stunDuration: 1000,
    },
  },
};

export const BEASTS: Record<string, BeastDefinition> = {
  // ============================================
  // STARTER BEASTS (5)
  // ============================================

  rock_tortoise: {
    id: 'rock_tortoise',
    name: 'Rock Tortoise',
    silhouette: 'dome',
    weight: 'heavy',
    speed: 0.7,
    health: 130,
    attackPower: 1.1,
    attackRange: 50,
    attackCooldown: 600,
    abilityCooldown: 10000,
    quirk: 'Shell retreats when low health',
    special: 'Shell Slam - Briefly becomes immovable boulder, then releases shockwave',
    unlock: 'starter',
    color: '#6b7280',
    description: 'Slow and steady. Takes a lot to move this one.',
    ability: ABILITIES.shell_slam,
  },

  honk_goose: {
    id: 'honk_goose',
    name: 'Honk Goose',
    silhouette: 'long-neck',
    weight: 'light',
    speed: 1.3,
    health: 80,
    attackPower: 0.8,
    attackRange: 70,
    attackCooldown: 400,
    abilityCooldown: 6000,
    quirk: 'Randomly honks (alerting nearby players)',
    special: 'Flap Burst - Short dash with knockback at the end',
    unlock: 'starter',
    color: '#f8fafc',
    description: 'Fast, annoying, and proud of it. HONK.',
    ability: ABILITIES.flap_burst,
  },

  stretchy_ferret: {
    id: 'stretchy_ferret',
    name: 'Stretchy Ferret',
    silhouette: 'long',
    weight: 'light',
    speed: 1.4,
    health: 70,
    attackPower: 0.7,
    attackRange: 90,
    attackCooldown: 350,
    abilityCooldown: 5000,
    quirk: 'Hitbox stretches when moving fast',
    special: 'Slinky Dash - 300px invulnerable dash forward',
    unlock: 'starter',
    color: '#d97706',
    description: 'The fastest and squishiest. A noodle with teeth.',
    ability: ABILITIES.slinky_dash,
  },

  boom_frog: {
    id: 'boom_frog',
    name: 'Boom Frog',
    silhouette: 'squat',
    weight: 'medium',
    speed: 0.9,
    health: 90,
    attackPower: 1.3,
    attackRange: 40,
    attackCooldown: 700,
    abilityCooldown: 8000,
    quirk: 'Bounces slightly with each hop',
    special: 'Tongue Lash - Slime glob that creates slow zone',
    unlock: 'starter',
    color: '#22c55e',
    description: 'Explosive personality. Literally.',
    ability: ABILITIES.tongue_lash,
  },

  punch_crab: {
    id: 'punch_crab',
    name: 'Punch Crab',
    silhouette: 'wide',
    weight: 'medium',
    speed: 0.8,
    health: 100,
    attackPower: 1.4,
    attackRange: 45,
    attackCooldown: 550,
    abilityCooldown: 7000,
    quirk: 'Can only move sideways (strafes)',
    special: 'One-Two Punch - Double hit, second punch has huge knockback',
    unlock: 'starter',
    color: '#ef4444',
    description: 'Walks funny but hits hard. Real hard.',
    ability: ABILITIES.one_two_punch,
  },

  // ============================================
  // ACHIEVEMENT BEASTS (10)
  // ============================================

  sleepy_bear: {
    id: 'sleepy_bear',
    name: 'Sleepy Bear',
    silhouette: 'round-large',
    weight: 'heavy',
    speed: 0.6,
    health: 150,
    attackPower: 1.5,
    attackRange: 55,
    attackCooldown: 800,
    abilityCooldown: 15000,
    quirk: 'Occasionally yawns (brief vulnerability)',
    special: 'Hibernate Rage - Invulnerable for 3s, then massive AOE',
    unlock: 'achievement',
    color: '#78350f',
    description: 'Just wants to nap. Stop bothering it.',
    ability: ABILITIES.hibernate_rage,
  },

  mirror_monkey: {
    id: 'mirror_monkey',
    name: 'Mirror Monkey',
    silhouette: 'humanoid',
    weight: 'light',
    speed: 1.2,
    health: 75,
    attackPower: 0.9,
    attackRange: 55,
    attackCooldown: 450,
    abilityCooldown: 12000,
    quirk: 'Mimics last beast that hit it (visual only)',
    special: 'Quick Swap - Teleport to nearest enemy',
    unlock: 'achievement',
    color: '#a855f7',
    description: 'Imitation is the sincerest form of annoyance.',
    ability: ABILITIES.quick_swap,
  },

  glass_rhino: {
    id: 'glass_rhino',
    name: 'Glass Rhino',
    silhouette: 'wedge',
    weight: 'heavy',
    speed: 1.1,
    health: 60,
    attackPower: 1.6,
    attackRange: 60,
    attackCooldown: 650,
    abilityCooldown: 6000,
    quirk: 'Shatters on death (area damage)',
    special: 'Crystal Shard - Fast, high damage single shot',
    unlock: 'achievement',
    color: '#06b6d4',
    description: 'Fast and devastating. Also extremely fragile.',
    ability: ABILITIES.crystal_shard,
  },

  panic_octopus: {
    id: 'panic_octopus',
    name: 'Panic Octopus',
    silhouette: 'blob-tentacles',
    weight: 'medium',
    speed: 0.85,
    health: 95,
    attackPower: 0.6,
    attackRange: 80,
    attackCooldown: 300,
    abilityCooldown: 9000,
    quirk: 'Attack hits in random directions (8 tentacles)',
    special: 'Ink Bomb - Creates vision-blocking splat',
    unlock: 'achievement',
    color: '#ec4899',
    description: 'Eight arms of pure anxiety.',
    ability: ABILITIES.ink_bomb,
  },

  unicycle_giraffe: {
    id: 'unicycle_giraffe',
    name: 'Unicycle Giraffe',
    silhouette: 'tall-thin',
    weight: 'light',
    speed: 1.0,
    health: 85,
    attackPower: 0.9,
    attackRange: 100,
    attackCooldown: 500,
    abilityCooldown: 7000,
    quirk: 'Wobbles constantly (hard to hit, hard to aim)',
    special: 'Wheel Boost - 2x speed + knockback immunity',
    unlock: 'achievement',
    color: '#fbbf24',
    description: 'Majestic. Unstable. On a unicycle.',
    ability: ABILITIES.wheel_boost,
  },

  electric_eel: {
    id: 'electric_eel',
    name: 'Electric Eel (With Legs)',
    silhouette: 'serpentine',
    weight: 'medium',
    speed: 1.1,
    health: 80,
    attackPower: 0.8,
    attackRange: 65,
    attackCooldown: 400,
    abilityCooldown: 10000,
    quirk: 'Leaves electric trail when damaged',
    special: 'Chain Lightning - Piercing bolt that chains to nearby enemies',
    unlock: 'achievement',
    color: '#3b82f6',
    description: 'Yes, it has legs. No, we won\'t explain.',
    ability: ABILITIES.chain_lightning,
  },

  pigeon_king: {
    id: 'pigeon_king',
    name: 'Pigeon King',
    silhouette: 'bird-crowned',
    weight: 'light',
    speed: 1.15,
    health: 70,
    attackPower: 0.7,
    attackRange: 50,
    attackCooldown: 350,
    abilityCooldown: 8000,
    quirk: 'Crown falls off when hit (must retrieve for full power)',
    special: 'Royal Volley - 3 slow homing pigeons',
    unlock: 'achievement',
    color: '#64748b',
    description: 'Rules the rooftops. Demands respect.',
    ability: ABILITIES.royal_volley,
  },

  screaming_goat: {
    id: 'screaming_goat',
    name: 'Screaming Goat',
    silhouette: 'quadruped',
    weight: 'medium',
    speed: 1.0,
    health: 100,
    attackPower: 1.1,
    attackRange: 50,
    attackCooldown: 500,
    abilityCooldown: 5000,
    quirk: 'Screams when taking damage (distracting everyone)',
    special: 'AAAAAH - Stun + knockback cone',
    unlock: 'achievement',
    color: '#f5f5f4',
    description: 'The scream. You know the one.',
    ability: ABILITIES.scream,
  },

  slime_cow: {
    id: 'slime_cow',
    name: 'Slime Cow',
    silhouette: 'blob-horned',
    weight: 'heavy',
    speed: 0.75,
    health: 120,
    attackPower: 0.9,
    attackRange: 60,
    attackCooldown: 550,
    abilityCooldown: 11000,
    quirk: 'Leaves slime trail (slows enemies)',
    special: 'Moo-cus Missile - Large slow glob, big slow zone',
    unlock: 'achievement',
    color: '#84cc16',
    description: 'Part cow. Part slime. All gross.',
    ability: ABILITIES.moocus_missile,
  },

  cactus_cat: {
    id: 'cactus_cat',
    name: 'Cactus Cat',
    silhouette: 'feline-spiky',
    weight: 'light',
    speed: 1.25,
    health: 65,
    attackPower: 0.75,
    attackRange: 40,
    attackCooldown: 300,
    abilityCooldown: 6000,
    quirk: 'Damages enemies that touch it',
    special: 'Spine Barrage - 5 needles in spread pattern',
    unlock: 'achievement',
    color: '#16a34a',
    description: 'Cute from a distance. Keep your distance.',
    ability: ABILITIES.spine_barrage,
  },

  // ============================================
  // PREMIUM BEASTS (5)
  // ============================================

  time_hamster: {
    id: 'time_hamster',
    name: 'Time Hamster',
    silhouette: 'small-round',
    weight: 'light',
    speed: 1.3,
    health: 60,
    attackPower: 0.8,
    attackRange: 45,
    attackCooldown: 400,
    abilityCooldown: 15000,
    quirk: 'Occasionally glitches position (teleports tiny distance)',
    special: 'Rewind - Teleport to position from 3 seconds ago',
    unlock: 'premium',
    color: '#f472b6',
    description: 'Controls time. Still runs on a wheel.',
    ability: ABILITIES.rewind,
  },

  tax_evasion_raccoon: {
    id: 'tax_evasion_raccoon',
    name: 'Tax Evasion Raccoon',
    silhouette: 'bandit',
    weight: 'medium',
    speed: 1.1,
    health: 85,
    attackPower: 0.85,
    attackRange: 55,
    attackCooldown: 450,
    abilityCooldown: 9000,
    quirk: 'Steals small amount of enemy health on hit',
    special: 'Shadow Step - Invisibility + teleport',
    unlock: 'premium',
    color: '#374151',
    description: 'The IRS will never find him here.',
    ability: ABILITIES.shadow_step,
  },

  cosmic_duck: {
    id: 'cosmic_duck',
    name: 'Cosmic Duck',
    silhouette: 'duck-ethereal',
    weight: 'medium',
    speed: 0.95,
    health: 90,
    attackPower: 1.0,
    attackRange: 60,
    attackCooldown: 500,
    abilityCooldown: 10000,
    quirk: 'Phases through hazards (but not players)',
    special: 'Quasar Blast - Slightly homing fireball',
    unlock: 'premium',
    color: '#7c3aed',
    description: 'Transcended mortality. Still goes quack.',
    ability: ABILITIES.quasar_blast,
  },

  reality_dog: {
    id: 'reality_dog',
    name: 'Reality Dog',
    silhouette: 'canine-glitchy',
    weight: 'medium',
    speed: 1.05,
    health: 95,
    attackPower: 1.0,
    attackRange: 55,
    attackCooldown: 480,
    abilityCooldown: 12000,
    quirk: 'Appearance glitches constantly (distracting)',
    special: 'Phase Shift - Intangible + fast for 2s',
    unlock: 'premium',
    color: '#f97316',
    description: 'Is it a good boy? Was it ever a boy? Reality is uncertain.',
    ability: ABILITIES.phase_shift,
  },

  the_human: {
    id: 'the_human',
    name: 'The Human',
    silhouette: 'humanoid-plain',
    weight: 'medium',
    speed: 1.0,
    health: 100,
    attackPower: 1.0,
    attackRange: 50,
    attackCooldown: 500,
    abilityCooldown: 8000,
    quirk: 'Completely average (unnerving to other beasts)',
    special: 'Existential Crisis - Stun all nearby',
    unlock: 'premium',
    color: '#fcd34d',
    description: 'The most terrifying beast of all. A human.',
    ability: ABILITIES.existential_crisis,
  },

  // ============================================
  // NEW BEASTS (10 more)
  // ============================================

  laser_cat: {
    id: 'laser_cat',
    name: 'Laser Cat',
    silhouette: 'feline',
    weight: 'light',
    speed: 1.25,
    health: 85,
    attackPower: 0.9,
    attackRange: 45,
    attackCooldown: 400,
    abilityCooldown: 6000,
    quirk: 'Eyes glow red when charging laser',
    special: 'Laser Beam - Piercing beam of destruction',
    unlock: 'starter',
    color: '#ef4444',
    description: 'Pew pew. The internet was right about cats and lasers.',
    ability: ABILITIES.laser_beam,
  },

  bouncy_bunny: {
    id: 'bouncy_bunny',
    name: 'Bouncy Bunny',
    silhouette: 'rabbit',
    weight: 'light',
    speed: 1.4,
    health: 75,
    attackPower: 0.7,
    attackRange: 40,
    attackCooldown: 350,
    abilityCooldown: 5000,
    quirk: 'Always seems to be hopping',
    special: 'Super Bounce - Leap and land with impact',
    unlock: 'starter',
    color: '#f472b6',
    description: 'Boing boing boing! Can\'t catch what you can\'t touch.',
    ability: ABILITIES.super_bounce,
  },

  thunder_bear: {
    id: 'thunder_bear',
    name: 'Thunder Bear',
    silhouette: 'bear',
    weight: 'heavy',
    speed: 0.75,
    health: 140,
    attackPower: 1.4,
    attackRange: 60,
    attackCooldown: 700,
    abilityCooldown: 9000,
    quirk: 'Fur crackles with static electricity',
    special: 'Thunder Stomp - Massive electric shockwave',
    unlock: 'achievement',
    color: '#facc15',
    description: 'When thunder meets bear, everyone loses.',
    ability: ABILITIES.thunder_stomp,
  },

  ninja_squirrel: {
    id: 'ninja_squirrel',
    name: 'Ninja Squirrel',
    silhouette: 'rodent',
    weight: 'light',
    speed: 1.35,
    health: 70,
    attackPower: 0.8,
    attackRange: 35,
    attackCooldown: 300,
    abilityCooldown: 4000,
    quirk: 'Disappears into shadows when still',
    special: 'Acorn Barrage - Rapid fire nut assault',
    unlock: 'starter',
    color: '#78350f',
    description: 'Silent but deadly. And nutty.',
    ability: ABILITIES.acorn_barrage,
  },

  rocket_penguin: {
    id: 'rocket_penguin',
    name: 'Rocket Penguin',
    silhouette: 'bird-fat',
    weight: 'medium',
    speed: 0.9,
    health: 100,
    attackPower: 1.0,
    attackRange: 45,
    attackCooldown: 500,
    abilityCooldown: 7000,
    quirk: 'Waddles awkwardly but rockets beautifully',
    special: 'Rocket Boost - Blast forward at mach speed',
    unlock: 'achievement',
    color: '#0ea5e9',
    description: 'Who needs to fly when you can rocket?',
    ability: ABILITIES.rocket_boost,
  },

  sonic_bat: {
    id: 'sonic_bat',
    name: 'Sonic Bat',
    silhouette: 'bat',
    weight: 'light',
    speed: 1.3,
    health: 80,
    attackPower: 0.85,
    attackRange: 40,
    attackCooldown: 400,
    abilityCooldown: 8000,
    quirk: 'Echolocates constantly (annoying)',
    special: 'Sonic Screech - Disorienting sound attack',
    unlock: 'achievement',
    color: '#6366f1',
    description: 'REEEEEEEEE! Heard that? Neither did they.',
    ability: ABILITIES.sonic_screech,
  },

  bubble_fish: {
    id: 'bubble_fish',
    name: 'Bubble Fish',
    silhouette: 'fish',
    weight: 'light',
    speed: 1.1,
    health: 85,
    attackPower: 0.75,
    attackRange: 40,
    attackCooldown: 450,
    abilityCooldown: 6000,
    quirk: 'Floats slightly above ground in a water bubble',
    special: 'Bubble Blast - Trapping bubble projectiles',
    unlock: 'starter',
    color: '#22d3ee',
    description: 'Blub blub. Surprisingly effective out of water.',
    ability: ABILITIES.bubble_blast,
  },

  ghost_fox: {
    id: 'ghost_fox',
    name: 'Ghost Fox',
    silhouette: 'canine',
    weight: 'light',
    speed: 1.2,
    health: 90,
    attackPower: 0.9,
    attackRange: 45,
    attackCooldown: 400,
    abilityCooldown: 10000,
    quirk: 'Slightly transparent at all times',
    special: 'Spirit Walk - Become ethereal',
    unlock: 'premium',
    color: '#c4b5fd',
    description: 'Is it a fox? Is it a ghost? Yes.',
    ability: ABILITIES.spirit_walk,
  },

  magnet_mole: {
    id: 'magnet_mole',
    name: 'Magnet Mole',
    silhouette: 'mole',
    weight: 'medium',
    speed: 0.85,
    health: 110,
    attackPower: 1.1,
    attackRange: 50,
    attackCooldown: 550,
    abilityCooldown: 9000,
    quirk: 'Metal objects stick to fur',
    special: 'Magnetic Pull - Drag enemies toward you',
    unlock: 'achievement',
    color: '#94a3b8',
    description: 'Attractive personality. Literally.',
    ability: ABILITIES.magnetic_pull,
  },

  disco_peacock: {
    id: 'disco_peacock',
    name: 'Disco Peacock',
    silhouette: 'bird-fancy',
    weight: 'medium',
    speed: 1.0,
    health: 95,
    attackPower: 0.95,
    attackRange: 45,
    attackCooldown: 450,
    abilityCooldown: 11000,
    quirk: 'Feathers constantly shimmer with rainbow colors',
    special: 'Disco Flash - Blinding light show',
    unlock: 'premium',
    color: '#d946ef',
    description: 'Fabulous AND deadly. The best combo.',
    ability: ABILITIES.disco_flash,
  },
};

// Export abilities for use elsewhere
export { ABILITIES };

// Get all beast IDs by unlock type
export const STARTER_BEASTS = Object.values(BEASTS)
  .filter((b) => b.unlock === 'starter')
  .map((b) => b.id);

export const ACHIEVEMENT_BEASTS = Object.values(BEASTS)
  .filter((b) => b.unlock === 'achievement')
  .map((b) => b.id);

export const PREMIUM_BEASTS = Object.values(BEASTS)
  .filter((b) => b.unlock === 'premium')
  .map((b) => b.id);

export const ALL_BEAST_IDS = Object.keys(BEASTS);

// Helper to get beast by ID
export function getBeast(id: string): BeastDefinition | undefined {
  return BEASTS[id];
}

// Validate beast ID
export function isValidBeast(id: string): boolean {
  return id in BEASTS;
}
